"""Effect-size reporting alongside statistical significance.

For every ANN method vs the exact Flat baseline (paired per-query arrays from
eval_modalities.py), computes:
  - Cohen's d for paired samples: mean(diff) / sd(diff)
  - Cliff's delta (non-parametric, robust to the heavy zero-inflation of
    per-query ranking metrics)
with conventional magnitude interpretations (negligible/small/medium/large).

Output: results/analyses/effect_sizes/effect_sizes.csv
(the presentation table is generated by tables_paper.py)
"""
import argparse
import sys
from pathlib import Path

import pandas as pd

from bootstrap_significance import load_perquery, METRICS
from utils.metrics import cohens_d_paired, cliffs_delta, effect_size_interpretation
from utils.paths import RESULTS
from utils.result_io import (preflight_output, write_dataframe_atomic,
                             ResultExistsError)

SCRIPT = "effect_size_tables"
KEY = ["dataset", "weighting", "dim", "modality", "method", "baseline",
       "metric", "seed"]


def main():
    ap = argparse.ArgumentParser(
        description="Paired Cohen's d and Cliff's delta of every ANN method "
                    "vs the exact Flat baseline, per metric.")
    ap.add_argument("--perquery_dir", default=RESULTS["perquery"])
    ap.add_argument("--out_dir", default=RESULTS["effect_sizes"])
    ap.add_argument("--baseline_method", default="flat")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--write_mode", default="fail_if_exists",
                    choices=["fail_if_exists", "replace", "merge"])
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_path = out_dir / "effect_sizes.csv"
    try:
        preflight_output(out_path, args.write_mode)
    except (ResultExistsError, ValueError) as e:
        print(f"[{SCRIPT}] ERROR: {e}")
        sys.exit(1)

    print(f"[{SCRIPT}] starting...")
    print(f"[{SCRIPT}] input path: {args.perquery_dir}")
    print(f"[{SCRIPT}] output path: {out_path}")

    runs = load_perquery(args.perquery_dir)
    if not runs:
        print(f"[{SCRIPT}] ERROR: no per-query files found in "
              f"{args.perquery_dir}. Run run_revision_experiments.py first.")
        sys.exit(1)

    rows = []
    for (dataset, weighting, dim, modality, method), rec in sorted(
            runs.items(), key=lambda kv: tuple(map(str, kv[0]))):
        if method == args.baseline_method:
            continue
        base = runs.get((dataset, weighting, dim, modality,
                         args.baseline_method))
        if base is None:
            print(f"[{SCRIPT}] WARN: no {args.baseline_method} baseline for "
                  f"{dataset}/{weighting}/d{dim}/{modality}; skipping {method}.")
            continue
        for metric in METRICS:
            if metric == "ann_recall_vs_exact":
                continue
            arrays, base_arrays = rec["arrays"], base["arrays"]
            if metric not in arrays or metric not in base_arrays:
                continue
            a, b = arrays[metric], base_arrays[metric]
            if a.shape != b.shape:
                continue
            d = cohens_d_paired(a, b)
            delta = cliffs_delta(a, b, seed=args.seed)
            rows.append({
                "dataset": dataset, "weighting": weighting, "dim": dim,
                "modality": modality, "method": method,
                "baseline": args.baseline_method, "metric": metric,
                "mean_diff": float(a.mean() - b.mean()),
                "cohens_d": d,
                "cohens_d_magnitude": effect_size_interpretation(d, "cohens_d"),
                "cliffs_delta": delta,
                "cliffs_delta_magnitude": effect_size_interpretation(
                    delta, "cliffs_delta"),
                "n": int(a.size),
                "seed": rec["seed"] if rec["seed"] is not None else args.seed,
            })

    df = pd.DataFrame(rows)
    out_dir.mkdir(parents=True, exist_ok=True)
    write_dataframe_atomic(df, out_path, mode=args.write_mode,
                           key=KEY, sort_by=KEY)
    print(f"[{SCRIPT}] output path: {out_path} ({len(df)} rows)")
    print(f"[{SCRIPT}] completed.")


if __name__ == "__main__":
    main()
