"""Generate the paper tables (CSV + Markdown + LaTeX) from measured results.

Pure post-processing: reads the CSVs produced by the pipeline and reshapes
them. Missing inputs are skipped with a warning so partial runs still yield
partial tables. Never fabricates values.

Inputs (all optional, generated by earlier stages):
    results/main/summary_main.csv
    results/calibration_sensitivity/calibration_sensitivity.csv
    results/bootstrap/bootstrap_cis.csv
    results/bootstrap/paired_tests.csv
    results/effect_sizes/effect_sizes.csv
    results/paper_tables/dataset_stats.csv        (from dataset_stats.py)

Reviewer-limitation module outputs (also optional; tables are refreshed from
whichever of the module's summary/all CSVs exists):
    results/embedding_sensitivity/, results/pq_diagnostics/,
    results/exposure_analysis/, results/scale_stress/,
    results/optional_backends/, results/energy/,
    ann_decision_framework + claim_support_audit tables.

Outputs: results/paper_tables/table_*.{csv,md,tex} and refreshed module tables
"""
import argparse
from pathlib import Path

import pandas as pd

from utils.paths import RESULTS
from utils.reporting import write_table

SCRIPT = "tables_paper"


def _read(path):
    p = Path(path)
    if not p.is_file():
        print(f"[{SCRIPT}] WARN: {p} not found; skipping dependent tables.")
        return None
    return pd.read_csv(p)


def table_main_quality(summary, out_dir):
    cols = ["dataset", "weighting", "modality", "method",
            "ndcg_at_k_mean", "recall_at_k_mean", "hr_at_k_mean", "mrr_at_k_mean",
            "ann_recall_vs_exact_at_k_mean", "latency_p50_ms", "latency_p95_ms"]
    df = summary[[c for c in cols if c in summary.columns]].copy()
    df = df.sort_values(["dataset", "modality", "method"])
    return write_table(df, out_dir / "table_main_quality")


def table_long_tail(summary, out_dir):
    cols = ["dataset", "weighting", "modality", "method",
            "coverage_at_k", "gini_exposure", "long_tail_exposure", "long_tail_uplift"]
    df = summary[[c for c in cols if c in summary.columns]].copy()
    df = df.sort_values(["dataset", "modality", "method"])
    return write_table(df, out_dir / "table_long_tail_exposure")


def table_calibration(cal, out_dir):
    df = cal.copy().sort_values(["dataset", "method", "target_recall"])
    cols = ["dataset", "weighting", "method", "target_recall", "target_reached",
            "param_name", "calibrated_param_value", "achieved_recall_vs_exact",
            "latency_p50_ms", "latency_p95_ms"]
    df = df[[c for c in cols if c in df.columns]]
    return write_table(df, out_dir / "table_calibration_sensitivity")


def table_significance(tests, effects, out_dir):
    """Merged significance + effect-size table (NDCG focus)."""
    keys = ["dataset", "weighting", "modality", "method", "metric"]
    t = tests.copy()
    if effects is not None:
        e = effects[keys + ["cohens_d", "cohens_d_magnitude",
                            "cliffs_delta", "cliffs_delta_magnitude"]]
        t = t.merge(e, on=keys, how="left")
    t = t[t["metric"].isin(["ndcg", "recall", "hr"])]
    cols = keys + ["mean_diff", "ci_low", "ci_high", "p_value", "significant_at_0.05",
                   "cohens_d", "cohens_d_magnitude", "cliffs_delta", "cliffs_delta_magnitude"]
    t = t[[c for c in cols if c in t.columns]].sort_values(keys)
    return write_table(t, out_dir / "table_significance_effect_sizes")


def table_ci(cis, out_dir):
    df = cis[cis["metric"].isin(["ndcg", "recall", "hr"])].copy()
    df = df.sort_values(["dataset", "modality", "metric", "method"])
    return write_table(df, out_dir / "table_bootstrap_cis")


# (module primary CSV, paper-table base name) for the reviewer-limitation
# modules; the module's own summary in paper_tables wins, else the raw
# *_all.csv is tabulated. Missing inputs are skipped.
MODULE_TABLES = [
    (f"{RESULTS['paper_tables']}/embedding_backbone_sensitivity_summary.csv",
     f"{RESULTS['embedding_sensitivity']}/embedding_backbone_sensitivity_all.csv",
     "embedding_backbone_sensitivity_summary"),
    (f"{RESULTS['paper_tables']}/pq_diagnostics_summary.csv",
     f"{RESULTS['pq_diagnostics']}/pq_diagnostics_all.csv",
     "pq_diagnostics_summary"),
    (f"{RESULTS['paper_tables']}/exposure_analysis_summary.csv",
     f"{RESULTS['exposure_analysis']}/exposure_analysis_all.csv",
     "exposure_analysis_summary"),
    (f"{RESULTS['paper_tables']}/scale_stress_summary.csv",
     f"{RESULTS['scale_stress']}/scale_stress_all.csv",
     "scale_stress_summary"),
    (f"{RESULTS['paper_tables']}/optional_ann_backend_comparison.csv",
     f"{RESULTS['optional_backends']}/optional_ann_backend_comparison.csv",
     "optional_ann_backend_comparison"),
    (f"{RESULTS['paper_tables']}/energy_measurement_summary.csv",
     f"{RESULTS['energy']}/energy_measurement_all.csv",
     "energy_measurement_summary"),
    (f"{RESULTS['paper_tables']}/ann_decision_framework_scores.csv",
     f"{RESULTS['deployment_guidance']}/ann_decision_framework_scores.csv",
     "ann_decision_framework_scores"),
    (f"{RESULTS['paper_tables']}/claim_support_audit.csv",
     None,
     "claim_support_audit"),
]


def refresh_module_tables(out_dir):
    """Re-emit md/tex for reviewer-limitation module tables from whichever
    source CSV exists (summary preferred, raw *_all.csv fallback)."""
    written = []
    for summary_csv, all_csv, name in MODULE_TABLES:
        src = None
        if summary_csv and Path(summary_csv).is_file():
            src = summary_csv
        elif all_csv and Path(all_csv).is_file():
            src = all_csv
        if src is None:
            print(f"[{SCRIPT}] WARN: no input for module table '{name}'; skipping.")
            continue
        df = pd.read_csv(src)
        written += write_table(df, out_dir / name)
    return written


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--summary_csv", default=f"{RESULTS['main']}/summary_main.csv")
    ap.add_argument("--calibration_csv",
                    default=f"{RESULTS['calibration_sensitivity']}/calibration_sensitivity.csv")
    ap.add_argument("--bootstrap_cis_csv", default=f"{RESULTS['bootstrap']}/bootstrap_cis.csv")
    ap.add_argument("--paired_tests_csv", default=f"{RESULTS['bootstrap']}/paired_tests.csv")
    ap.add_argument("--effect_sizes_csv", default=f"{RESULTS['effect_sizes']}/effect_sizes.csv")
    ap.add_argument("--out_dir", default=RESULTS["paper_tables"])
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    print(f"[{SCRIPT}] starting...")
    for p in (args.summary_csv, args.calibration_csv, args.bootstrap_cis_csv,
              args.paired_tests_csv, args.effect_sizes_csv):
        print(f"[{SCRIPT}] input path: {p}")
    print(f"[{SCRIPT}] output path: {out_dir}")
    out_dir.mkdir(parents=True, exist_ok=True)

    written = []
    summary = _read(args.summary_csv)
    if summary is not None:
        written += table_main_quality(summary, out_dir)
        written += table_long_tail(summary, out_dir)

    cal = _read(args.calibration_csv)
    if cal is not None:
        written += table_calibration(cal, out_dir)

    cis = _read(args.bootstrap_cis_csv)
    if cis is not None:
        written += table_ci(cis, out_dir)

    tests = _read(args.paired_tests_csv)
    effects = _read(args.effect_sizes_csv)
    if tests is not None:
        written += table_significance(tests, effects, out_dir)

    written += refresh_module_tables(out_dir)

    for p in written:
        print(f"[{SCRIPT}] output path: {p}")
    if not written:
        print(f"[{SCRIPT}] WARN: no input CSVs found; nothing generated.")
    print(f"[{SCRIPT}] completed.")


if __name__ == "__main__":
    main()
